"""
Questionnaire Engine
Manages session state and the 9-field collection flow.

Key changes:
  - Question TEXT is never hardcoded — it is generated by the LLM based on
    patient profile, already-collected answers, and database options.
  - "Other" and ANY non-option input is validated via LLM before storing.
  - Procedure + city options are loaded dynamically from Supabase.
"""
import json
import os
import uuid
from typing import Optional

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage


# ── Question field definitions (keys + types only — NO hardcoded text) ────────
# text is generated by LLM at runtime via generate_question_text()

QUESTION_FIELDS = [
    {"key": "selected_procedure", "field_type": "str",          "allow_other": True,  "force_map": False},
    {"key": "age",                "field_type": "age",           "allow_other": False},
    {"key": "gender",             "field_type": "str",           "allow_other": True},
    {"key": "city",               "field_type": "str",           "allow_other": True},
    {"key": "comorbidities",      "field_type": "comorbidities", "allow_other": True},
    {"key": "smoking",            "field_type": "bool",          "allow_other": False},
    {"key": "insurance_status",   "field_type": "str",           "allow_other": False},
    {"key": "budget_limit",       "field_type": "budget",        "allow_other": True},
    {"key": "room_preference",    "field_type": "str",           "allow_other": False},
]

# Static options for fields that have fixed choices (injected at session start)
STATIC_OPTIONS = {
    "age":              ["Under 20", "20-40", "41-60", "61-80", "Above 80"],
    "gender":           ["Male", "Female"],
    "comorbidities":    ["Diabetes", "Hypertension", "Both (Diabetes & Hypertension)", "None"],
    "smoking":          ["Yes", "No"],
    "insurance_status": ["Private", "Government", "None"],
    "budget_limit":     ["Below ₹50,000", "₹50,000 – ₹1,00,000", "₹1,00,000 – ₹2,00,000", "Above ₹2,00,000"],
    "room_preference":  ["General", "Semi-private", "Private"],
}

# Value maps
AGE_MAP = {
    "under 20": 15, "20-40": 30, "41-60": 50, "61-80": 70, "above 80": 85,
}
BUDGET_MAP = {
    "below ₹50,000": 50000.0,
    "₹50,000 – ₹1,00,000": 100000.0,
    "₹1,00,000 – ₹2,00,000": 200000.0,
    "above ₹2,00,000": 300000.0,
}
COMORBIDITY_MAP = {
    "diabetes": ["diabetes"],
    "hypertension": ["hypertension"],
    "both (diabetes & hypertension)": ["diabetes", "hypertension"],
    "none": [],
}

# In-memory session store
sessions: dict = {}


# ── LLM helper ────────────────────────────────────────────────────────────────

def _get_llm() -> ChatGroq:
    return ChatGroq(
        model="llama-3.3-70b-versatile",
        groq_api_key=os.environ.get("GROQ_API_KEY"),
        temperature=0.3,
    )


# ── LLM question text generator ───────────────────────────────────────────────

def generate_question_text(
    field_key: str,
    collected_answers: dict,
    patient_context: str = "",
    procedure_options: list = None,
    city_options: list = None,
    is_first_question: bool = False,
) -> str:
    """
    Asks Groq to write a single conversational question for the given field.
    - Only uses patient name/context on the VERY FIRST question.
    - Subsequent questions must be plain, direct, with no name or intro.
    - Strictly enforces one short question sentence — no preamble.
    """
    field_descriptions = {
        "selected_procedure": "the medical procedure or treatment the patient needs",
        "age":                "the patient's age",
        "gender":             "the patient's gender",
        "city":               "the city where the patient wants treatment",
        "comorbidities":      "any health conditions the patient has (diabetes, hypertension, etc.)",
        "smoking":            "whether the patient smokes",
        "insurance_status":   "the patient's health insurance status",
        "budget_limit":       "the patient's budget for the treatment",
        "room_preference":    "the patient's preferred type of hospital room",
    }
    context_str = json.dumps({k: str(v) for k, v in collected_answers.items()}, ensure_ascii=False)

    llm = _get_llm()

    # Patient name/context is ONLY given to LLM on the very first question.
    # After that, strictly no names — just a plain focused question.
    if is_first_question and patient_context:
        persona_rule = (
            "This is the FIRST question after greeting. You may briefly reference the patient's context "
            "(e.g. their known condition if relevant to this field), but do NOT use their name again — "
            "the greeting already introduced them. Keep it warm but concise."
        )
        context_block = f"Patient context (use sparingly): {patient_context}"
    else:
        # Never include patient name or personal references after the first question
        persona_rule = (
            "This is a follow-up question. Do NOT address the patient by name. "
            "Do NOT start with 'I see', 'I understand', 'Based on', or any filler phrase. "
            "Just ask the question directly and naturally."
        )
        context_block = ""

    # Extra context for dynamic fields
    extra = ""
    if field_key == "selected_procedure" and procedure_options:
        extra = f"Available procedures: {', '.join(procedure_options[:10])} (patient can also type their own)."
    elif field_key == "city" and city_options:
        extra = f"Cities covered: {', '.join(city_options)}."

    system_msg = SystemMessage(content=(
        "You are a concise healthcare cost assistant in India. "
        "Your ONLY job is to output ONE short question sentence — nothing else. "
        "Rules:\n"
        "1. Output EXACTLY one question. No intro. No explanation. No trailing note.\n"
        "2. The question must be the LAST and ONLY sentence in your response.\n"
        "3. Do NOT use the patient's name. Do NOT repeat info already collected.\n"
        "4. Use ₹ for rupees if relevant. Keep it under 20 words.\n"
        f"5. {persona_rule}"
    ))
    human_msg = HumanMessage(content=(
        f"Field to ask: {field_descriptions.get(field_key, field_key)}\n"
        f"Already collected: {context_str}\n"
        f"{context_block}\n"
        f"{extra}\n"
        f"Output the question:"
    ))
    try:
        response = llm.invoke([system_msg, human_msg])
        # Strip any stray preamble — take only the last sentence if multiple returned
        text = response.content.strip()
        # If LLM returned multiple sentences, take the last one (the actual question)
        sentences = [s.strip() for s in text.replace("\n", " ").split(".") if s.strip()]
        question_sentences = [s for s in sentences if "?" in s]
        if question_sentences:
            return question_sentences[0].strip() + "?"
        # Fallback: return whatever was generated
        return text if text else fallbacks_map().get(field_key, f"Please provide your {field_key}.")
    except Exception:
        return fallbacks_map().get(field_key, f"Please provide your {field_key}.")


def fallbacks_map() -> dict:
    """Static fallback question text used only when Groq completely fails."""
    return {
        "selected_procedure": "What medical procedure or treatment are you looking for?",
        "age":                "What is your age group?",
        "gender":             "What is your gender?",
        "city":               "Which city are you in?",
        "comorbidities":      "Do you have any existing health conditions?",
        "smoking":            "Do you currently smoke?",
        "insurance_status":   "What is your insurance status?",
        "budget_limit":       "What is your approximate budget for the treatment?",
        "room_preference":    "What type of hospital room do you prefer?",
    }


# ── Session management ─────────────────────────────────────────────────────────

def create_session(
    prefilled_answers: dict = None,
    procedure_options: list = None,
    city_options: list = None,
    patient_context: str = "",
) -> str:
    """
    Create a new questionnaire session.
    - prefilled_answers: from patient_service (skip known questions)
    - procedure_options: from Supabase procedures table
    - city_options: from Supabase hospitals table
    - patient_context: text describing patient profile (for LLM question generation)
    """
    sid = str(uuid.uuid4())
    prefilled = prefilled_answers or {}

    # Resolve options for each field
    resolved_fields = []
    for field in QUESTION_FIELDS:
        f = dict(field)
        if f["key"] == "selected_procedure":
            f["options"] = procedure_options or []
        elif f["key"] == "city":
            f["options"] = city_options or []
        else:
            f["options"] = STATIC_OPTIONS.get(f["key"], [])
        resolved_fields.append(f)

    sessions[sid] = {
        "answers": dict(prefilled),
        "fields": resolved_fields,
        "current_field_index": 0,
        "awaiting_other_text": False,
        "dynamic_options": None,
        "patient_context": patient_context,
        "procedure_options": procedure_options or [],
        "city_options": city_options or [],
        "questions_asked": 0,          # tracks how many questions have been sent to user
    }
    _skip_prefilled(sid)
    return sid


def _skip_prefilled(session_id: str):
    """Advance index past already-answered fields."""
    state = sessions[session_id]
    fields = state["fields"]
    while state["current_field_index"] < len(fields):
        f = fields[state["current_field_index"]]
        if f["key"] in state["answers"]:
            state["current_field_index"] += 1
        else:
            break


def get_next_question(session_id: str) -> Optional[dict]:
    """
    Return the current unanswered question with LLM-generated text.
    First question may briefly reference patient context.
    All subsequent questions are plain and direct — no patient name.
    Returns None if all fields are answered.
    """
    state = sessions[session_id]
    idx = state["current_field_index"]
    fields = state["fields"]
    if idx >= len(fields):
        return None

    f = fields[idx]
    is_first = state.get("questions_asked", 0) == 0

    question_text = generate_question_text(
        field_key=f["key"],
        collected_answers=state["answers"],
        patient_context=state.get("patient_context", "") if is_first else "",
        procedure_options=state.get("procedure_options"),
        city_options=state.get("city_options"),
        is_first_question=is_first,
    )
    state["questions_asked"] = state.get("questions_asked", 0) + 1

    opts = f["options"] + (["Other"] if f.get("allow_other") else [])
    return {
        "question": question_text,
        "question_key": f["key"],
        "options": opts,
        "allow_other": f.get("allow_other", False),
        "awaiting_free_text": False,
    }


# ── Answer processing ──────────────────────────────────────────────────────────

def process_answer(session_id: str, answer: str) -> dict:
    """
    Process a user answer. Returns next question dict or final collected_answers.
    Validates ALL non-option answers via LLM — nothing is stored raw.
    """
    state = sessions.get(session_id)
    if not state:
        return {"error": "Session not found or expired. Please start a new session."}

    fields = state["fields"]
    idx = state["current_field_index"]
    if idx >= len(fields):
        return {"type": "final", "collected_answers": state["answers"]}

    f = fields[idx]

    # ── Case 1: awaiting free text after "Other" ──────────────────────────────
    if state["awaiting_other_text"]:
        groq_result = _validate_via_llm(
            question_key=f["key"],
            question_text=f"asking about {f['key']}",
            user_input=answer,
            existing_options=f["options"],
            force_map=f.get("force_map", False),
        )
        state["awaiting_other_text"] = False
        if groq_result.get("mapped_to") is not None:
            _store_answer(state, f, groq_result["mapped_to"])
            state["current_field_index"] += 1
            _skip_prefilled(session_id)
        else:
            new_opts = groq_result.get("new_options", [answer])
            state["dynamic_options"] = new_opts
            return {
                "type": "question",
                "question": "Please choose the most relevant option:",
                "question_key": f["key"],
                "options": new_opts + ["Other"],
                "allow_other": True,
                "awaiting_free_text": False,
            }

    # ── Case 2: picking from Groq-generated dynamic options ───────────────────
    elif state["dynamic_options"] is not None:
        if answer.lower() == "other":
            state["dynamic_options"] = None
            state["awaiting_other_text"] = True
            return {
                "type": "question",
                "question": f"Please describe your {f['key']}:",
                "question_key": f["key"],
                "options": [],
                "allow_other": False,
                "awaiting_free_text": True,
            }
        _store_answer(state, f, answer)
        state["dynamic_options"] = None
        state["current_field_index"] += 1
        _skip_prefilled(session_id)

    # ── Case 3: normal answer — validate if not matching a known option ───────
    else:
        if answer.lower() == "other":
            state["awaiting_other_text"] = True
            return {
                "type": "question",
                "question": f"Please describe your {f['key']}:",
                "question_key": f["key"],
                "options": [],
                "allow_other": False,
                "awaiting_free_text": True,
            }

        # Check if answer exactly matches a known option (case-insensitive)
        option_lower = [o.lower() for o in f["options"]]
        if answer.lower() in option_lower:
            # Exact match — store directly
            _store_answer(state, f, answer)
        elif f.get("allow_other", False):
            # Non-matching free text + allow_other — validate via LLM
            groq_result = _validate_via_llm(
                question_key=f["key"],
                question_text=f"asking about {f['key']}",
                user_input=answer,
                existing_options=f["options"],
                force_map=f.get("force_map", False),
            )
            if groq_result.get("mapped_to") is not None:
                _store_answer(state, f, groq_result["mapped_to"])
            else:
                new_opts = groq_result.get("new_options", [answer])
                state["dynamic_options"] = new_opts
                return {
                    "type": "question",
                    "question": "I found a few related options. Please pick the best match:",
                    "question_key": f["key"],
                    "options": new_opts + ["Other"],
                    "allow_other": True,
                    "awaiting_free_text": False,
                }
        else:
            # No allow_other — store as-is (field like smoking/room_preference with strict options)
            _store_answer(state, f, answer)

        state["current_field_index"] += 1
        _skip_prefilled(session_id)

    # ── Check completion ───────────────────────────────────────────────────────
    if state["current_field_index"] >= len(fields):
        return {"type": "final", "collected_answers": state["answers"]}

    # Generate next question via LLM
    # Always a follow-up — no patient name, no context (those belong only to the first question)
    next_f = fields[state["current_field_index"]]
    question_text = generate_question_text(
        field_key=next_f["key"],
        collected_answers=state["answers"],
        patient_context="",         # ← never pass patient context in follow-up questions
        procedure_options=state.get("procedure_options"),
        city_options=state.get("city_options"),
        is_first_question=False,    # ← always False here; first question is only from get_next_question()
    )
    opts = next_f["options"] + (["Other"] if next_f.get("allow_other") else [])
    return {
        "type": "question",
        "question": question_text,
        "question_key": next_f["key"],
        "options": opts,
        "allow_other": next_f.get("allow_other", False),
        "awaiting_free_text": False,
    }


# ── LLM validator (replaces _call_groq_for_other + validates all free text) ───

def _parse_json_safe(text: str) -> Optional[dict]:
    """
    Robustly parse JSON from LLM output.
    Handles markdown fences, trailing noise, and partial responses.
    """
    import re
    # Strip markdown fences
    text = re.sub(r"```(?:json)?\s*", "", text).strip().rstrip("`").strip()
    # Direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Find first JSON object in the text
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    return None


def _validate_via_llm(
    question_key: str,
    question_text: str,
    user_input: str,
    existing_options: list,
    force_map: bool = False,
) -> dict:
    """
    Validates ANY free-text input via LLM.
    - For 'selected_procedure': normalizes capitalization only.
    - For other fields: maps to existing option OR generates 3-5 sub-options.
    Returns {"mapped_to": str|None, "new_options": list[str]}
    """
    # Procedure: accept as-is, just normalize to title case
    if question_key == "selected_procedure":
        return {"mapped_to": user_input.strip().title(), "new_options": []}

    # Comorbidities: handle 'none/no/nil' directly without LLM
    if question_key == "comorbidities" and user_input.strip().lower() in ("none", "no", "nil", "nothing", "n/a"):
        return {"mapped_to": "None", "new_options": []}

    llm = _get_llm()
    system_msg = SystemMessage(content=(
        "You are a medical assistant for a healthcare cost estimation system in India. "
        "Interpret patient responses. Either map to one existing option OR generate "
        "3-5 specific, relevant sub-options. Respond ONLY with valid JSON — no markdown, no extra text."
    ))
    human_msg = HumanMessage(content=(
        f'Field: "{question_key}"\n'
        f"Existing options: {existing_options}\n"
        f'Patient typed: "{user_input}"\n\n'
        f"If input clearly matches one existing option, return it. Otherwise generate 3-5 new specific options.\n"
        f'Respond ONLY with: {{"mapped_to": null or "<exact existing option>", "new_options": ["...", "..."]}}'
    ))
    try:
        response = llm.invoke([system_msg, human_msg])
        result = _parse_json_safe(response.content)
        if result and ("mapped_to" in result or "new_options" in result):
            return result
        return {"mapped_to": None, "new_options": [user_input]}
    except Exception:
        return {"mapped_to": None, "new_options": [user_input]}


# ── Answer normalizer ──────────────────────────────────────────────────────────

def _store_answer(state: dict, field: dict, raw_answer: str):
    """Normalizes and stores a validated answer into session state."""
    key = field["key"]
    field_type = field["field_type"]
    val = str(raw_answer).strip()

    if field_type == "age":
        # Accept both bucket ("20-40") and raw integer ("34")
        mapped = AGE_MAP.get(val.lower())
        if mapped is not None:
            state["answers"]["age"] = mapped
        else:
            try:
                state["answers"]["age"] = int(float(val.replace(",", "")))
            except ValueError:
                state["answers"]["age"] = 30

    elif field_type == "budget":
        budget = BUDGET_MAP.get(val.lower())
        if budget is None:
            try:
                budget = float(val.replace(",", "").replace("₹", "").replace(" ", ""))
            except ValueError:
                budget = 100000.0
        state["answers"]["budget_limit"] = budget

    elif field_type == "comorbidities":
        lower_val = val.lower()
        if lower_val in ("none", "no", "nil", "nothing", "n/a"):
            state["answers"]["comorbidities"] = []
        else:
            state["answers"]["comorbidities"] = COMORBIDITY_MAP.get(
                lower_val, [lower_val]  # store raw if not in map
            )

    elif field_type == "bool":
        state["answers"]["smoking"] = val.lower() in ("yes", "true", "1", "smoker")

    elif key == "selected_procedure":
        # Preserve title case for DB lookup — ilike handles case anyway
        state["answers"][key] = val.title()

    else:
        # For city, gender, insurance, room: lowercase is fine for ilike queries
        state["answers"][key] = val.lower()


# ── Final assembly ─────────────────────────────────────────────────────────────

def build_chat_request(answers: dict) -> dict:
    """Convert collected session answers into a ChatRequest-compatible dict."""
    return {
        "age":               answers.get("age", 30),
        "gender":            answers.get("gender", "male"),
        "city":              answers.get("city", "pune"),
        "insurance_status":  answers.get("insurance_status", "none"),
        "budget_limit":      answers.get("budget_limit", 100000.0),
        "selected_procedure": answers.get("selected_procedure", ""),
        "comorbidities":     answers.get("comorbidities", []),
        "smoking":           answers.get("smoking", False),
        "room_preference":   answers.get("room_preference", "general"),
    }


def build_known_summary(session_id: str) -> str:
    """Returns a short human-readable summary of collected answers so far."""
    state = sessions.get(session_id)
    if not state:
        return ""
    answers = state.get("answers", {})
    if not answers:
        return ""

    LABEL_MAP = {
        "selected_procedure": "Procedure",
        "age":                "Age",
        "gender":             "Gender",
        "city":               "City",
        "comorbidities":      "Conditions",
        "smoking":            "Smoker",
        "insurance_status":   "Insurance",
        "budget_limit":       "Budget",
        "room_preference":    "Room",
    }
    parts = []
    for key, label in LABEL_MAP.items():
        val = answers.get(key)
        if val is None:
            continue
        if isinstance(val, list):
            display = ", ".join(val) if val else "None"
        elif isinstance(val, bool):
            display = "Yes" if val else "No"
        elif isinstance(val, float) and key == "budget_limit":
            display = f"₹{val:,.0f}"
        else:
            display = str(val).title()
        parts.append(f"{label}: {display}")

    return "📋 Known so far: " + " | ".join(parts) if parts else ""
